version: '3.8'
name: balancer-core
services:
  db:
    hostname: db
    image: postgres:15-alpine
    ports:
      - '49153:5432'
    environment:
      - POSTGRES_USER=core
      - POSTGRES_PASSWORD=local-dev
      - POSTGRES_DB=core-db
  wiremock:
    hostname: wiremock
    image: wiremock/wiremock:2.35.0-alpine
    ports:
      - '49154:8443'
      - '49155:8444'
    volumes:
      - ../../code/boot/src/test/resources/wiremock/:/home/wiremock
    command:
      - --port=8443
      - --https-port=8444
      - --global-response-templating
